# Generated by Django 5.1.15 on 2026-01-29 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoritesS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.series"
                    ),
                ),
                (
                    "user_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoritesM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.movies"
                    ),
                ),
                (
                    "user_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoritesE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.series"
                    ),
                ),
                (
                    "user_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.profile"
                    ),
                ),
            ],
        ),
    ]
