# Generated by Django 5.2.11 on 2026-03-02 11:29

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_profile_favoritess_favoritesm_favoritese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_file',
            field=models.FileField(blank=True, null=True, upload_to=media.models.movies_files_by_id),
        ),
    ]
