# Generated by Django 5.2.11 on 2026-03-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_movies_movie_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritesm',
            name='movie_fk',
        ),
        migrations.RemoveField(
            model_name='favoritesm',
            name='user_fk',
        ),
        migrations.RemoveField(
            model_name='favoritess',
            name='series_fk',
        ),
        migrations.RemoveField(
            model_name='favoritess',
            name='user_fk',
        ),
        migrations.AddField(
            model_name='profile',
            name='priv',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='FavoritesE',
        ),
        migrations.DeleteModel(
            name='FavoritesM',
        ),
        migrations.DeleteModel(
            name='FavoritesS',
        ),
    ]
